<?php
include './backend/connection.php';

$database = new DatabaseConnection();
$con = $database->getConnection();


// Input text containing the list of cities and states// Define the array structure
$states = [
    'Delhi' => ['Bawana'],
    'Bengaluru' => ['Bengaluru'],
    'Goa' => [
        'Mormugao',
        'Ponda',
        'Panaji',
        'Margao',
        'Vasco da gama',
        'Mapusa',
        'Baga',
        'Calangute',
        'Anjuna',
        'Canacona',
        'Bardez',
        'Colva',
        'Arambol',
        'Sanguem',
        'Bicholim',
        'Sattari',
        'Porvorim',
        'Valpoi',
        'Pernem',
        'Cuncolim'
    ],
    'Rajasthan' => [
        'Jaipur',
        'Ajmer',
        'Alwar',
        'Amer',
        'Banaswara',
        'Barmer',
        'Bharatpur',
        'Bhilwara',
        'Bhiwadi',
        'Bikaner',
        'Bhadra',
        'Bundi',
        'Chittaurgarh',
        'Kishangarh',
        'Didwana',
        'Nohar',
        'Pratapgarh',
        'Churu',
        'Dungarpur',
        'Jaisalmer',
        'Jhalawar',
        'Jodhpur',
        'Kota',
        'Kumbhalgarh',
        'Mount Abu',
        'Ganganagar',
        'Hanumangarh',
        'Gangapur',
        'Jalore',
        'Sojat',
        'Nathdwara',
        'Niwai',
        'Nagaur',
        'Neemrana',
        'Pali',
        'Pushkar',
        'Ranakpur',
        'Sawai Madhopur',
        'Shekhawati',
        'Sikar',
        'Udaipur',
        'Tonk',
        'Baran',
        'Dausa',
        'Laxmangarh',
        'Merta',
        'Ladnun',
        'Rawatbhata',
        'Dholpur'
    ],
    'Assam' => [
        "Baksa",
        "Barpeta",
        "Biswanath",
        "Bongaigaon",
        "Cachar",
        "Charaideo",
        "Chirang",
        "Darrang",
        "Dhemaji",
        "Dhubri",
        "Dibrugarh",
        "Dima Hasao (North Cachar Hills)",
        "Goalpara",
        "Golaghat",
        "Hailakandi",
        "Hojai",
        "Jorhat",
        "Kamrup",
        "Kamrup Metropolitan",
        "Karbi Anglong",
        "Karimganj",
        "Kokrajhar",
        "Lakhimpur",
        "Majuli",
        "Morigaon",
        "Nagaon",
        "Nalbari",
        "Sivasagar",
        "Sonitpur",
        "South Salamara-Mankachar",
        "Tinsukia",
        "Udalguri",
        "West Karbi Anglong",
        "Rangia",
        "Dispur",
        "Guwahati"
    ],
    "Bihar" => [
        "Patna",
        "Purbi Champaran",
        "Muzaffarpur",
        "Madhubani",
        "Gaya",
        "Samastipur",
        "Saran",
        "Darbhanga",
        "Pashchim Champaran",
        "Vaishali",
        "Sitamarhi",
        "Siwan",
        "Purnia",
        "Katihar",
        "Bhagalpur",
        "Begusarai",
        "Rohtas",
        "Nalanda",
        "Araria",
        "Bhojpur",
        "Gopalganj",
        "Aurangabad",
        "Supaul",
        "Nawada",
        "Banka",
        "Madhepura",
        "Saharsa",
        "Jamui",
        "Buxar",
        "Kishanganj",
        "Khagaria",
        "Kaimur",
        "Munger",
        "Jehanabad",
        "Lakhisarai",
        "Arwal",
        "Sheohar",
        "Sheikhpura",
        "Bihar sharif",
        "Rajgir",
        "Sasaram",
        "Arrah",
        "Chhapra",
        "Hajipur",
        "Bettiah",
        "Bagaha",
        "Hilsa",
        "Bhabua",
        "Bakhtiyarpur",
        "Khagaul"
    ],
    'Gujarat' => [
        "Ahmedabad",
        "Amreli",
        "Anand",
        "Aravalli",
        "Banaskantha",
        "Bharuch",
        "Bhavnagar",
        "Botad",
        "Chhota Udaipur",
        "Dahod",
        "Dang",
        "Devbhoomi Dwarka",
        "Gandhinagar",
        "Gir Somnath",
        "Jamnagar",
        "Junagadh",
        "Kachchh",
        "Kheda",
        "Mahisagar",
        "Mehsana",
        "Morbi",
        "Narmada",
        "Navsari",
        "Panch Mahals",
        "Patan",
        "Porbandar",
        "Rajkot",
        "Sabarkantha",
        "Surat",
        "Surendranagar",
        "Tapi",
        "Vadodara",
        "Valsad",
        "Bhuj",
        "Palanpur",
        "Vapi",
        "Port blair",
        "Nadiad"
    ],
    'Haryana' => [
        "Ambala",
        "Bhiwani",
        "Faridabad",
        "Fatehabad",
        "Gurgaon",
        "Hisar",
        "Jhajjar",
        "Jind",
        "Kaithal",
        "Karnal",
        "Kurukshetra",
        "Mahendragarh",
        "Mewat",
        "Palwal",
        "Panchkula",
        "Panipat",
        "Rewari",
        "Rohtak",
        "Sirsa",
        "Sonipat",
        "Yamunanagar",
        "Bahadurgar",
        "Hansi-",
        "Narnaul",
        "Sohna"
    ],
    'Himachal Pradesh' => [
        "Bilaspur",
        "Chamba",
        "Hamirpur",
        "Kangra",
        "Kinnaur",
        "Kullu",
        "Lahaul and Spiti",
        "Mandi",
        "Shimla",
        "Sirmaur",
        "Solan",
        "Una",
        "Manali",
        "Dalhousie",
        "Palampur",
        "Sundernagar"
    ], 'Karnataka' => [
        "Belgaum",
        "Mysore",
        "Tumkur",
        "Gulbarga",
        "Bellary",
        "Bijapur",
        "Dakshina Kannada",
        "Davanagere",
        "Raichur",
        "Bagalkot",
        "Dharwad",
        "Mandya",
        "Hassan",
        "Shimoga",
        "Bidar",
        "Chitradurga",
        "Haveri",
        "Kolar",
        "Uttara Kannada",
        "Koppal",
        "Chikkaballapura",
        "Udupi",
        "Yadgir",
        "Chikmagalur",
        "Ramanagara",
        "Gadag",
        "Chamarajanagar",
        "Bangalore Rural",
        "Kodagu",
        "Mangalore",
        "Hubli",
        "Davangere",
        "Hospet",
        "Badami",
        "Bhadravathi",
        "Ranebennur",
        "Karwar",
        "Hampi",
        "Madikeri",
        "Vijayapura"
    ], 'Kerala' => [
        "Alappuzha",
        "Ernakulam",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Malappuram",
        "Palakkad",
        "Pathanamthitta",
        "Thiruvananthapuram",
        "Thrissur",
        "Wayanad",
        "Kochi",
        "Varkala",
        "Munnar",
        "Punalur",
        "Taliparamba"
    ],
    'Maharashtra' => [
        "Mumbai",
        "Akola",
        "Alibag",
        "Amravati",
        "Beed-city",
        "Bhiwandi",
        "Chandrapur",
        "Chiplun",
        "Jalna",
        "Dombivli",
        "Khandala",
        "Kolhapur",
        "Latur",
        "Lavasa",
        "Lonavala",
        "Malegaon",
        "Matheran",
        "Nanded",
        "Navi Mumbai",
        "Pandharpur",
        "Panvel",
        "Sangli",
        "Satara",
        "Vajreshwari",
        "Washim",
        "Nagpur",
        "Pune",
        "Baramati",
        "Raigad",
        "Jejuri",
        "Bhor",
        "Saswad",
        "Talegaon dabhade",
        "Panchgani",
        "Mahabaleshwar",
        "Kamshet",
        "Nashik",
        "Solapur",
        "Thane",
        "Jalgaon",
        "Ahmednagar",
        "Parbhani",
        "Ichalkaranji",
        "Bhusawal",
        "Karad",
        "Hinjewadi",
        "Dhule"
    ], 'Manipur' => [
        "Bishnupur",
        "Chandel",
        "Churachandpur",
        "Imphal East",
        "Imphal West",
        "Jiribam",
        "Kakching",
        "Kamjong",
        "Kangpokpi",
        "Noney",
        "Pherzawl",
        "Senapati",
        "Tamenglong",
        "Tengnoupal",
        "Thoubal",
        "Ukhrul"
    ], 'Meghalaya' => [
        "East Garo Hills",
        "Williamnagar East Jaintia Hills",
        "Khliehriat East Khasi Hills",
        "Shillong North Garo Hills",
        "Resubelpara Ri-Bhoi",
        "Nongpoh South Garo Hills",
        "Baghmara South West Garo Hills",
        "Ampati South West Khasi Hills",
        "Mawkyrwat West Garo Hills",
        "Tura West Jaintia Hills",
        "Jowai West Khasi Hills",
        "Nongstoin"
    ], 'Mizoram' => [
        "Aizawl",
        "Champhai",
        "Kolasib",
        "Lawngtlai",
        "Lunglei",
        "Mamit",
        "Saiha",
        "Serchhip"
    ], 'Nagaland' => [
        "Dimapur",
        "Kiphire",
        "Kohima",
        "Longleng",
        "Mokokchung",
        "Mon",
        "Peren",
        "Phek",
        "Tuensang",
        "Wokha",
        "Zunheboto"
    ], 'Odisha' => [
        "Angul",
        "Balangir",
        "Bargarh",
        "Boudh",
        "Deogarh",
        "Gajapati",
        "Jagatsinghpur",
        "Jharsuguda",
        "Kandhamal",
        "Keonjhar",
        "Koraput",
        "Mayurbhanj",
        "Nayagarh",
        "Puri",
        "Sambalpur",
        "Sundargarh",
        "Balasore",
        "Bhadrak",
        "Cuttack",
        "Dhenkanal",
        "Ganjam",
        "Jajpur",
        "Kalahandi",
        "Kendrapara",
        "Khurda",
        "Malkangiri",
        "Nabarangpur",
        "Nuapada",
        "Rayagada",
        "Sonepur",
        "Bhubaneswar",
        "Rourkela",
        "Berhampur",
        "Jeypore",
        "Barbil",
        "Bhawanipatna",
        "Talcher",
        "Burla",
        "Joda"
    ], 'Sikkim' => [
        "East Sikkim",
        "Gangtok North Sikkim",
        "Mangan South Sikkim",
        "Namchi West Sikkim",
        "Geyzing"
    ], 'Tamil Nadu' => [
        "Kancheepuram",
        "Vellore",
        "Thiruvallur",
        "Salem",
        "Viluppuram",
        "Coimbatore",
        "Tirunelveli",
        "Madurai",
        "Tiruchirappalli",
        "Cuddalore",
        "Tiruppur",
        "Tiruvannamalai",
        "Thanjavur",
        "Erode",
        "Dindigul",
        "Virudhunagar",
        "Krishnagiri",
        "Kanniyakumari",
        "Thoothukkudi",
        "Namakkal",
        "Pudukkottai",
        "Nagapattinam",
        "Dharmapuri",
        "Ramanathapuram",
        "Sivaganga",
        "Thiruvarur",
        "Theni",
        "Karur",
        "Ariyalur",
        "The Nilgiris",
        "Perambalur",
        "Chennai",
        "Pollachi",
        "Hosur",
        "Kodaikanal",
        "Sivakasi",
        "Tiruchengode",
        "Kanyakumari"
    ], 'Telangana' => [
        "Hyderabad",
        "Karimnagar",
        "Mahaboobnagar",
        "Medak",
        "Rangareddy",
        "Warangal",
        "Nalgonda",
        "Khammam",
        "Adilabad",
        "Nizamabad"
    ], 'Uttar Pradesh' => [
        "Agra",
        "Aligarh",
        "Allahabad",
        "Azamgarh",
        "Ballia",
        "Basti",
        "Bijnor",
        "Chandausi",
        "Deoria",
        "Etawah",
        "Ferozpur",
        "Gokul",
        "Gorakhpur",
        "Hapur",
        "Jaunpur",
        "Kanpur",
        "Lucknow",
        "Mirzapur",
        "Muzaffarnagar",
        "Pilibhit",
        "Sambhal",
        "Sitapur",
        "Unnao",
        "Badaun",
        "Bareilly",
        "Bhadohi",
        "Chandauli",
        "Chitrakut",
        "Etah",
        "Faizabad",
        "Ghaziabad",
        "Gonda",
        "Greater Noida",
        "Hardoi",
        "Jhansi",
        "Lalitpur",
        "Meerut",
        "Moradabad",
        "Noida",
        "Saharanpur",
        "Sarnath",
        "Sultanpur",
        "Varanasi",
        "Raebareli",
        "Firozabad",
        "Shahjahanpur",
        "Mainpuri",
        "Rampur",
        "Amethi",
        "Ambedkar nagar",
        "Jalaun",
        "Kheri",
        "Baghpat",
        "Mau",
        "Bahraich",
        "Farrukhabad",
        "Chitrakoot"
    ], 'West Bengal' => [
        "Kolkata",
        "North Twenty Four Parganas",
        "South Twenty Four Parganas",
        "Barddhaman",
        "Murshidabad",
        "Paschim Medinipur",
        "Hugli",
        "Nadia",
        "Purba Medinipur",
        "Haora",
        "Maldah",
        "Jalpaiguri",
        "Bankura",
        "Birbhum",
        "Uttar Dinajpur",
        "Puruliya",
        "Koch Bihar",
        "Darjiling",
        "Dakshin Dinajpur",
        "Asansol",
        "Siliguri",
        "Durgapur",
        "Bardhaman",
        "Darjeeling",
        "Kalimpong"
    ], 'Andhra Pradesh' => [
        "East Godavari",
        "Guntur",
        "Krishna",
        "Visakhapatnam",
        "Chittoor",
        "Anantapur",
        "Kurnool",
        "Mahbubnagar",
        "West Godavari",
        "Prakasam",
        "Sri Potti Sriramulu Nellore",
        "YSR",
        "Srikakulam",
        "Vizianagaram",
        "Tirupati",
        "Vijayawada",
        "Amaravati",
        "Kakinada",
        "Rajahmundry",
        "Eluru",
        "Kadapa",
        "Ongole",
        "Machilipatnam",
        "Hindupur",
        "Madanapalle",
        "Bhimavaram",
        "Tadepalligude",
        "Guntakal",
        "Dharmavaram",
        "Chilakaluripet",
        "Narasaraopet",
        "Tanuku",
        "Nuzvid"
    ], 'Chhattisgarh' => [
        "Bhilai",
        "Kumhari",
        "Ratanpur",
        "Naya raipur",
        "Raigarh",
        "Raipur"
    ], 'Jharkhand' => [
        "Ranchi",
        "Bokaro",
        "Jamshedpur",
        "Dhanbad"
    ], 'Madhya Pradesh' => [
        "Bhopal",
        "Indore",
        "Jabalpur",
        "Sagar",
        "Gwalior",
        "Satna",
        "Rewa",
        "Burhanpur",
        "Ratlam",
        "Guna",
        "Mandu",
        "Hoshangabad",
        "Morena",
        "Khargone",
        "Chhatarpur",
        "Dhar",
        "Mhow",
        "Betul",
        "Raisen",
        "Dewas",
        "Bhind",
        "Chhindwara",
        "Vidisha",
        "Sehore",
        "Seoni",
        "Datia"
    ], 'Uttarakhand' => [
        "Dehradun",
        "Mussoorie",
        "Haldwani",
        "Rishikesh",
        "Nainital",
        "Rudrapur",
        "Roorkee"
    ], 'Arunachal Pradesh' => [
        "Itanagar",
        "Dharamshala",
        "Mcleod ganj"
    ], 'Jammu and Kashmir' => [
        "Srinagar",
        "Jammu",
        "Gulmarg",
        "Sonamarg",
        "Pahalgam",
        "Baramulla",
        "Anantnag"
    ], 'Lakshadweep' => [
        "Lakshadweep"
    ], 'Tripura' => [
        "Agartala"
    ]
    // Add more states and cities as needed
];

// Output the array
// foreach($states as $state=> $city){
   
// $query = $con->prepare("INSERT INTO states(state,cities) VALUES (?,?)");
// $cty = json_encode($city);
// $query->execute([$state,$cty]); 
// if($query){
//     if($query->rowCount() >0){
//         echo 'Inserted';
//     }else{
//         echo 'Failer';
//     }
// }else{
//     echo 'failed to Insert';
// }

// }
